### ISSUE TITLE
Module 'raft' not found error

### ISSUE THREAD

**Issue by zhaoyi1228** [YueWuHKUST/CVPR2022-Optimizing-Video-Prediction-via-Video-Frame-Interpolation#3]
Thank you for your great work!
I want to follow your work but when I was creating the environment, I suffered this error:

`Traceback (most recent call last):
  File "demo_optimization.py", line 92, in <module>
    flow_method = RAFT(model='kitti')
  File "/home/smbu/mediadisk/OVP/flownet.py", line 66, in __init__
    from raft import raft
ModuleNotFoundError: No module named 'raft'
`
I tried to use pip to install the 'raft' package, however, another error raised:
`ImportError: cannot import name 'raft' from 'raft'`

Can anyone help me with this problem? Thank you very much.

**Comment by zhaoyi1228** [comment]
In addition, I didn't find a raft package in the `environment.yaml`...

**Comment by kathrinawu** [comment]
Sorry that I missed the illustration here. https://github.com/princeton-vl/RAFT needed to be downloaded, and the pretrained models of RAFT are also needed. We use RAFT to compute the optical flow.
